### ISSUE TITLE
"Now Playing" Info not Showing

### ISSUE THREAD

**Issue by nandababa** [24hourkirtan/ionic-audio-streaming#5]
The current alpha version does not show "now playing" info after clicking the play button under Android 5.0.2 using an HTC One. @wkande confirmed this issue on his Samsung S4, not sure which Android version.

I cannot build the Android app on my Macbook due to permission problems which I still have to fix, but in the iOS simulator "now playing" info is displayed correctly. Wondering if it's working on an iOS device.

**Comment by wkande** [comment]
Here are both the Android and IOS screen shots.

IOS iPhone 6s Plus
<img src="https://cloud.githubusercontent.com/assets/3522283/12885576/3e73390e-ce24-11e5-866d-3488050e56f8.PNG" width="300" height="auto" />

Samsung S4
<img src="https://cloud.githubusercontent.com/assets/3522283/12885584/4663f59a-ce24-11e5-8e7b-aceb9604c45d.png" width="300" height="auto" />

**Comment by nandababa** [comment]
Thanks, is this from the simulator or from the physical devices?

**Comment by wkande** [comment]
The screen shots I put into two separate issues are all from actual devices.

**Comment by schmoofer** [comment]
Can you both try the APK I uploaded to the repo? I tested it on a couple of Android devices successfully. Didn't change any of the current code on the repo for it.

**Comment by wkande** [comment]
The test APK shows the title right away. The music starts to play at around 21 seconds. Samsung S4.

**Comment by schmoofer** [comment]
@wkande  That's odd, I generated the APK using the same code from the repo. Can you possibly copy&paste any console output using Chrome's browser inspector?

Also, can you tell me how long http://24hourkirtan.fm/ takes to start playing music?

**Comment by schmoofer** [comment]
@wkande I meant copy&pasting the console output for your version of the Android build where the title doesn't display.

The app fetches the title from a different endpoint of the Icecast server, not from the audio stream. They are independent from one another.

**Comment by wkande** [comment]
Moving comments about delay time to issue **#2 Play Button delay - Android device**.

**Comment by nandababa** [comment]
I just pulled the current state of the repository, ran `ionic state restore` and then `cordova build ios` successfully, but now I cannot even click the play button.
