### ISSUE TITLE
Plugin listing on the Wiki and package.json

### ISSUE THREAD

**Issue by wkande** [24hourkirtan/ionic-audio-streaming#6]
The Wiki details for setup have the user install 2 cordova plugins. 

cordova plugin add https://github.com/keosuofficial/cordova-audio-stream-plugin.git
cordova plugin add cordova-plugin-network-information

There are several plugins listed in the package.json file.  Should the WIKI include additional directives to install these as well? 

Also should we add the two plugins shown above to the package.json file?

"cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard"
  ]

**Comment by nandababa** [comment]
I think @schmoofer has to answer this. In general I think it's better to have more than less info on the WIKI.

**Comment by schmoofer** [comment]
Sure, we can do that. I actually wasn't aware of this feature since it was introduced less than a year ago. We can now run "ionic state restore" to reinstall all those plugins instead of installing them one by one.

Source:
http://www.raymondcamden.com/2015/04/20/ionic-adds-a-new-state-feature/
